dialect = "us"
auto_sync = true
update_check = true
sync_address = "http://10.10.5.11:8888"
sync_frequency = "1h"
search_mode = "daemon-fuzzy"
filter_mode = "global"
style = "auto"
history_format = "{time}\t{command}\t{duration}"
command_chaining = true
keymap_mode = "auto"
shells = "auto"

[daemon]
enabled = true
autostart = true
sync_frequency = 300
socket_path = "~/.local/share/atuin/atuin.sock"

[logs]
enabled = true
dir = "~/.atuin/logs"
level = "info"
retention = 4

[logs.ai]
enabled = true
file = "ai.log"
level = "info"
retention = 4

[logs.daemon]
enabled = true
file = "daemon.log"
level = "info"
retention = 4

[logs.search]
enabled = true
file = "search.log"
level = "info"
retention = 4

[ui]
columns = ["duration", "time", "command", "directory", "host" ]

syntax_highlight = true
