# =============================================================================
# refindtheme.conf
# Theme configuration file for the rEFInd boot menu
# =============================================================================

# rEFInd theme TTT from https://github.com/gutlessCGH/refindTTT.
# To successfully use rEFInd on NixOS, systemd-boot needs to be enabled as the default bootloader, with rEFInd installed as a package, then chainloading systemd-boot to properly display NixOS generations. After configuration and rebuild, run `sudo refind-install` to install rEFInd to the EFI System Partition. If successful, you should see the following in your terminal after running sudo refind-install:

# ShimSource is none
# Installing rEFInd on Linux....
# ESP was found at /boot using vfat
# Copied rEFInd binary files

# Copying sample configuration file as refind.conf; edit this file to configure
# rEFInd.

# Creating new NVRAM entry
# rEFInd is set as the default boot manager.
# Creating //boot/refind_linux.conf; edit it to adjust kernel options.

# Installation has completed successfully.

# To use a theme, download your chosen theme from https://refind-themes-collection.netlify.app/. Make "themes" directory: "sudo mkdir /boot/EFI/refind/themes", then copy your downloaded theme into the "themes" directory: "sudo cp -r [theme-name] /boot/EFI/refind/themes/". Finally, edit the default refind.conf file to add the theme.conf file at the end of the file: "sudo nano /boot/EFI/refind/refind.conf", and add the following lines: "include themes/[theme-name]/theme.conf". 

# I included this in my nix-config directory for version control, then copied it into the proper directory: "sudo cp -r ~/nix-config/modules/system/boot/refindthemes.conf /boot/EFI/refind/themes/". 

# See /modules/system/boot/default.nix for NixOS rEFInd configuration and installation details.

# Hide default refind text, ui elements
# All are hidden by default only for the sake of minimalism
hideui arrows,hints,label,badges

# Set icon directory
icons_dir themes/refindTTT/icons176

# Set background
# Custom backgrounds won't work well unless the center is entirely black
banner themes/refindTTT/backgrounds/background.png
banner_scale fillscreen

# Set icon sizes (default: 90, 176)
# Changing these will impact image quality; switch to 'theme.conf' in 'refind.conf' for larger icons
small_icon_size 90
big_icon_size 176

# Set background for selected option
# To hide text label change to 'selection_big_nolabels176.png', 'selection_small_nolabels176.png'
selection_big   themes/refindTTT/backgrounds/selection_big176.png
selection_small themes/refindTTT/backgrounds/selection_small176.png

# Set maximum icons to display at a time (divide screen width by 198)
max_tags 7

# Set delay before automatic boot
timeout 10
