# kitty.conf

# --- Admin ---
allow_hyperlinks yes
auto_reload_config 0.1
clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask
clipboard_max_size 512
editor nano
forward_stdio yes
shell_integration enabled

# --- Bell ---
enable_audio_bell yes
bell_on_tab "🔔 "
visual_bell_color none
visual_bell_duration 0.0
window_alert_on_bell yes

# --- Color Scheme ---
background_opacity 1.0
wayland_titlebar_color system

# --- Cursor ---
cursor_shape beam
cursor_blink_interval 0.5

# --- Font ---
font_family      FiraCode
font_size 11.0
font_features FiraCode-Retina +zero +onum
bold_font        FiraCode Nerd Font Mono
italic_font      FiraCode Nerd Font Mono
bold_italic_font FiraCode Nerd Font Mono
text_composition_strategy platform

# --- Mouse ---
copy_on_select clipboard
clear_selection_on_clipboard_loss yes
drag_threshold 5
focus_follows_mouse yes
mouse_hide_wait 3.0
paste_actions quote-urls-at-prompt,confirm
select_by_word_characters @-./_~?&=%+#
strip_trailing_spaces smart

# --- Performance ---
input_delay 3
sync_to_monitor yes 

# --- Scrollback ---
scrollback_lines 1000
scrollbar scrolled
scrollbar_interactive yes
scrollbar_jump_on_click yes
scrollbar_width 0.5
scrollbar_hover_width 1
scrollbar_handle_opacity 0.5
scrollbar_radius 0.3
scrollbar_gap 0.1
scrollbar_min_handle_height 1
scrollbar_hitbox_expansion 0.25
scrollbar_track_opacity 0

progress_bar bottom

momentum_scroll 0.96
touch_scroll_multiplier 1.0
wheel_scroll_multiplier 5.0
wheel_scroll_min_lines 1

# --- Tab Bar ---
tab_bar_align center
tab_bar_edge top
tab_bar_margin_height 0.0 0.0
tab_bar_margin_width 0.0
tab_bar_show_new_tab_button no
tab_bar_style slant
tab_powerline_style angled
tab_separator " ┇"
tab_switch_strategy previous
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{secure_input_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{title}"

# --- URLs ---
detect_urls yes
open_url_with default
show_hyperlink_targets never
underline_hyperlinks hover
url_color #0087bd
url_style curly
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh

# --- Window ---
placement_strategy center
window_border_width 0.5pt
window_resize_step_cells 2
window_resize_step_lines 2
window_title_bar top
window_title_bar_align center
window_title_bar_min_windows 1
window_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.window}{progress_percent}{title}"
